name: CICD

on: push
jobs:
  build-Android:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Android signing
        run: |   
           echo "${{ secrets.KEYSTORE }}" > CursoXamarinLive.keystore.asc   
           gpg -d --passphrase "${{ secrets.GPG_PASSWORD  }}" --batch CursoXamarinLive.keystore.asc > ./AwesomeXamarinApp/AwesomeXamarinApp.Android/CursoXamarinLive.keystore

      - name: Set Android version
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: ./AwesomeXamarinApp/AwesomeXamarinApp.Android/Properties/AndroidManifest.xml
          package-name: 'com.companyname.awesomexamarinapp'
          version-name: ${{ secrets.APP_VERSION }}
          version-code: ${{ github.run_number }}
          print-file: true
      
      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Build Android
        run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=CursoXamarinLive /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=CursoXamarinLive.keystore /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} ./AwesomeXamarinApp/AwesomeXamarinApp.Android/AwesomeXamarinApp.Android.csproj
        
      - name: Obtain Android APK file
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Xamarin Awesome App
          path: AwesomeXamarinApp/AwesomeXamarinApp.Android/bin/Release/com.companyname.awesomexamarinapp-Signed.apk
          
      - name: Setup App Center CLI
        run: npm install -g appcenter-cli

      - name: Upload Android app to App Center
        run: |
          appcenter distribute release --file ./AwesomeXamarinApp/AwesomeXamarinApp.Android/bin/Release/com.companyname.awesomexamarinapp-Signed.apk --app sergio115/LiveAwesomeXamarinApp --group Collaborators --token ${{ secrets.APP_CENTER_TOKEN }}
          appcenter distribute release --file ./AwesomeXamarinApp/AwesomeXamarinApp.Android/bin/Release/com.companyname.awesomexamarinapp-Signed.apk --app sergio115/LiveAwesomeXamarinApp --group BetaTesters --token ${{ secrets.APP_CENTER_TOKEN }}
         
